services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      php-fpm:
        condition: service_started
      mariadb:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  mariadb:
    image: mariadb:11.6
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: weather
      MARIADB_USER: weather
      MARIADB_PASSWORD: password
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
