services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm
      - mariadb
    restart: unless-stopped

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:11.6
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: weather
      MARIADB_USER: weather
      MARIADB_PASSWORD: password
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./docker/mariadb/:/docker-entrypoint-initdb.d

networks:
  backend:
    driver: bridge
